services:
  edge:
    image: m-voice-edge:v0.2.8
    pull_policy: never
    ports:
      - "5060:5060/udp"               # SIP
      - "8088:8088"                   # ARI/HTTP
      - "10000-10049:10000-10049/udp" # RTP
    volumes:
      - ./services/edge/etc/asterisk:/etc/asterisk
      - ./services/edge/var/lib/asterisk:/var/lib/asterisk
    restart: unless-stopped

  orchestrator:
    image: m-ai-orchestrator
    build:
      context: ./services/orchestrator
    ports:
      - "18080:8080"
    env_file:
      - ./config/.env
    volumes:
      - ./flows:/app/flows:ro
    restart: unless-stopped

# health check (HTTP/ARI reachable)
  # (indentation here assumes you're appending at file end; adjust if needed)
