services:
  edge:
    build:
      context: .
      dockerfile: services/edge/Dockerfile
    image: m-ai-edge
    restart: unless-stopped
    # optional: Logs auf Host
    # volumes:
    #   - ./logs:/var/log/mvoice

  orchestrator:
    image: m-ai-orchestrator
    restart: unless-stopped
    ports:
      - "18080:8080"
