services:
  edge:
    image: m-voice-edge:v0.2.8
    ports:
    - 5060:5060/udp
    - 8088:8088
    - 10000-10049:10000-10049/udp
    volumes:
    - ./services/edge/etc/asterisk:/etc/asterisk:ro
    - ./services/edge/var/lib/asterisk:/var/lib/asterisk
    - ./services/edge/var/log/asterisk:/var/log/asterisk
    - ./services/edge/var/log/mvoice:/var/log/mvoice
    restart: unless-stopped
    healthcheck:
      test:
      - CMD-SHELL
      - asterisk -rx 'http show status' >/dev/null 2>&1 && asterisk -rx 'pjsip show
        registrations' | tail -n +4 | tr -d '\r' | grep -qE 'Registered[[:space:]]*$'
      interval: 15s
      timeout: 3s
      retries: 8
      start_period: 45s
  orchestrator:
    image: m-ai-orchestrator
    build:
      context: ./services/orchestrator
    depends_on:
      edge:
        condition: service_healthy
    ports:
    - 18080:8080
    env_file:
    - ./config/.env
    volumes:
    - ./flows:/app/flows:ro
    restart: unless-stopped
